#!/usr/bin/env python3
"""Read services.yaml and emit build/services.generated.yaml.

The generated template is a parent stack containing one
AWS::CloudFormation::Stack per service, each pointing at templates/service.yaml.
scripts/deploy.sh runs `aws cloudformation package` against the output, which
rewrites the local TemplateURL paths into S3 URLs.
"""

import re
import sys
from pathlib import Path

import yaml

SERVICES_FILE = Path("services.yaml")
SERVICE_TEMPLATE = "../templates/service.yaml"
OUTPUT_FILE = Path("build/services.generated.yaml")


def logical_id(name):
    # CloudFormation logical ids are alphanumeric only.
    parts = re.split(r"[^a-zA-Z0-9]+", name)
    return "".join(part.capitalize() for part in parts if part) + "Stack"


def build_stack(service, config, priority):
    name = service["name"]
    exposure = service.get("exposure", "public")
    host_header = service.get("hostHeader", f"{name}.{config['domainName']}")
    return {
        "Type": "AWS::CloudFormation::Stack",
        "Properties": {
            "TemplateURL": SERVICE_TEMPLATE,
            "Parameters": {
                "SharedStackName": config["sharedStackName"],
                "ServiceName": name,
                "Port": service.get("port", 80),
                "HealthCheckPath": service.get("healthCheckPath", "/"),
                "HostHeader": host_header,
                "Exposure": exposure,
                "Priority": priority,
                "InstanceType": service.get("instanceType", "t3.micro"),
                "MinSize": service.get("minSize", 1),
                "MaxSize": service.get("maxSize", 3),
                "HostedZoneId": service.get("hostedZoneId", ""),
            },
        },
    }


def generate(config):
    resources = {}
    # Priorities are assigned per listener, not globally: a public and an
    # internal service can legally share the same priority number since they
    # sit on different listeners, and generate.py is the only place that can
    # compute this since CloudFormation cannot.
    next_priority = {"public": 1, "internal": 1}
    for service in config["services"]:
        exposure = service.get("exposure", "public")
        priority = next_priority[exposure]
        next_priority[exposure] += 1
        resources[logical_id(service["name"])] = build_stack(service, config, priority)
    return {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": "Generated by generate.py from services.yaml. Do not edit by hand.",
        "Resources": resources,
    }


def main():
    if not SERVICES_FILE.exists():
        sys.exit(f"{SERVICES_FILE} not found")
    with SERVICES_FILE.open() as f:
        config = yaml.safe_load(f)

    template = generate(config)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_FILE.open("w") as f:
        yaml.safe_dump(template, f, sort_keys=False)
    print(f"wrote {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
